apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: "1984"
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      database: fastapi_project_db1
    isDefault: false