{
 "title": "Fraud Detection Advanced",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "us_state",
    "query": "SELECT DISTINCT us_state FROM scores ORDER BY us_state"
   },
   {
    "name": "merch",
    "query": "SELECT DISTINCT merch FROM scores ORDER BY merch"
   }
  ]
 },
 "panels": [
  {
   "title": "TPS (транзакций в секунду)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created_at, '1s') as time, COUNT(*) as tps FROM scores WHERE $__timeFilter(created_at) and us_state IN (${us_state:singlequote}) AND merch IN (${merch:singlequote}) GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Плотность распределения скоров",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH buckets AS (SELECT WIDTH_BUCKET(score, 0, 1, 20) AS bucket, COUNT(*) AS cnt FROM scores WHERE $__timeFilter(created_at) AND us_state IN (${us_state:singlequote}) AND merch IN (${merch:singlequote}) GROUP BY bucket), total AS (SELECT SUM(cnt) AS total_cnt FROM buckets ) SELECT (bucket - 1) * (1.0/20) AS bucket_start, cnt::float / total_cnt AS density FROM buckets, total ORDER BY bucket"
    }
   ]
  },
  {
   "title": "Средняя доля фрода по cat_id (последние 1000 транзакций)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT cat_id, AVG(fraud_flag) as fraud_rate FROM (SELECT cat_id, fraud_flag FROM scores WHERE us_state IN (${us_state:singlequote}) AND merch IN (${merch:singlequote}) ORDER BY created_at DESC LIMIT 1000) sub GROUP BY cat_id ORDER BY fraud_rate DESC"
    }
   ]
  }
 ]
}